module.exports = {
  caseType:'versioned_satellite_analysis_release',
  initialState:'source_registered',
  states:['source_registered','license_verified','assets_versioned','analysis_queued','analysis_rendered','analysis_failed','analytic_qa','publication_approved','published','exported','closed'],
  createRoles:['imagery_analyst','project_manager'],
  assessmentRoles:['imagery_analyst','geospatial_reviewer','rights_reviewer','accessibility_reviewer'],
  auditRoles:['project_manager','rights_reviewer','auditor'],
  connectorRoles:['integration_operator','project_manager'],
  evidenceKinds:['provider_receipt','license_record','source_manifest','sensor_metadata','geospatial_asset_manifest','timeline_version','model_version','render_receipt','render_failure','fidelity_report','accessibility_report','moderation_report','watermark_disclosure','approval_record','publish_receipt','export_manifest','usage_receipt'],
  requiredSignals:['sourceVersion','sensorVersion','modelVersion','assetVersion','renderVersion','policyVersion','licenseStatus','consentStatus','geospatialFidelity','temporalAlignment','layoutScore','accessibilityStatus','moderationStatus','watermarkStatus','exportProfile'],
  professionalBoundary:'Satellite analyses are versioned media and analytic drafts. Qualified geospatial, rights, accessibility, and publication reviewers approve release; assessment never publishes or orders imagery.',
  connectors:[
    {name:'imagery_provider',purpose:'licensed imagery manifest and acquisition receipts'},
    {name:'rights_catalog',purpose:'license, consent, and usage versions'},
    {name:'object_storage',purpose:'encrypted asset pointers'},
    {name:'tile_cdn',purpose:'versioned tile delivery receipts'},
    {name:'model_provider',purpose:'queued analysis and render receipts'},
    {name:'translation',purpose:'locale and accessibility receipts'},
    {name:'publisher',purpose:'signed publish and export receipts'},
    {name:'usage',purpose:'metering and attribution receipts'},
  ],
  transitions:[
    {from:'source_registered',action:'verify_license',to:'license_verified',roles:['rights_reviewer'],requiresEvidence:true},
    {from:'license_verified',action:'lock_assets',to:'assets_versioned',roles:['imagery_analyst'],requiresEvidence:true},
    {from:'assets_versioned',action:'queue_analysis',to:'analysis_queued',roles:['imagery_analyst','integration_operator'],requiresEvidence:true},
    {from:'analysis_queued',action:'record_render',to:'analysis_rendered',roles:['integration_operator'],requiresEvidence:true},
    {from:'analysis_queued',action:'record_failure',to:'analysis_failed',roles:['integration_operator'],requiresEvidence:true},
    {from:'analysis_failed',action:'retry_analysis',to:'analysis_queued',roles:['imagery_analyst','integration_operator'],requiresEvidence:true},
    {from:'analysis_rendered',action:'submit_analytic_qa',to:'analytic_qa',roles:['geospatial_reviewer','accessibility_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'analytic_qa',action:'approve_publication',to:'publication_approved',roles:['project_manager','rights_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'publication_approved',action:'record_publish',to:'published',roles:['integration_operator','project_manager'],requiresEvidence:true,dualControl:true},
    {from:'publication_approved',action:'record_export',to:'exported',roles:['imagery_analyst','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'published',action:'close_release',to:'closed',roles:['project_manager'],requiresEvidence:true},
    {from:'exported',action:'close_release',to:'closed',roles:['project_manager'],requiresEvidence:true},
  ],
  acceptedFixture:{sourceVersion:'src1',sensorVersion:'sen1',modelVersion:'m1',assetVersion:'a1',renderVersion:'r1',policyVersion:'p1',licenseStatus:'verified',consentStatus:'verified',geospatialFidelity:0.99,temporalAlignment:0.98,layoutScore:0.97,accessibilityStatus:'passed',moderationStatus:'passed',watermarkStatus:'disclosed',exportProfile:'geospatial_accessible'},
  rejectedFixture:{sourceVersion:'src1',sensorVersion:'sen1',modelVersion:'m1',assetVersion:'a1',renderVersion:'r1',policyVersion:'p1',licenseStatus:'missing',consentStatus:'verified',geospatialFidelity:0.99,temporalAlignment:0.98,layoutScore:0.97,accessibilityStatus:'passed',moderationStatus:'passed',watermarkStatus:'disclosed',exportProfile:'geospatial_accessible'},
  readyDisposition:'independent_geospatial_publication_review_required',
  holdDisposition:'rights_fidelity_accessibility_or_export_hold',
  decisionField:'publishCommand',
  assess:(x)=>{const geo=Number(x.geospatialFidelity),temporal=Number(x.temporalAlignment),layout=Number(x.layoutScore);const ready=x.licenseStatus==='verified'&&x.consentStatus==='verified'&&geo>=0.98&&temporal>=0.95&&layout>=0.95&&x.accessibilityStatus==='passed'&&x.moderationStatus==='passed'&&x.watermarkStatus==='disclosed'&&['geospatial_accessible','geojson','geotiff'].includes(x.exportProfile);return{disposition:ready?'independent_geospatial_publication_review_required':'rights_fidelity_accessibility_or_export_hold',publishCommand:null,metrics:{geospatialFidelity:geo,temporalAlignment:temporal,layoutScore:layout},versions:{source:x.sourceVersion,sensor:x.sensorVersion,model:x.modelVersion,assets:x.assetVersion,render:x.renderVersion}};},
};
